[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.xml]
command = "scripts/xmlfmt.sh"
includes = ["*.xml"]

[formatter.yaml]
command = "yamlfmt"
options = ["-formatter", "retain_line_breaks=true"]
includes = ["*.yml"]
