name: Flatpak bundle

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  flatpak:
    if: ${{ !startsWith(github.head_ref, 'release-please--') && github.event.pull_request.user.login != 'weblate' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@v7

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: chorus.flatpak
          manifest-path: space.f1nn.chorus.dev.yml

      - if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: chorus.flatpak
